#!/usr/bin/env python3
"""
gen-p0calc-embeds.py — regenerate the Paper-F/Paper-H embedded data files for
the two explorer tools (OCS-P0-CALC-1 / P0-08, P0-09).

  tools/data/fF_v4_embed.js    <- paper/figs/fF_v4_pgf.txt  (PEXCL + eps95 curves)
                                 paper/figs/fF_v4_exclfrac.json (exact MC anchors)
  tools/data/fH_plane_embed.js <- paper/figs/fH_posterior_plane.json (marginal
                                 intervals + shipped cell counts)

The paper/figs directory lives in the OUTER repo, so this script CANNOT run in
site CI (a fresh site checkout has no ../paper). It is a workspace-level step:
run it once here whenever the paper regenerates its outputs, commit the
resulting embed files, and let scripts/check-p0calc-parity.py (which reads NO
outer-repo file) catch drift in CI.

Usage (from repo root):
    python scripts/gen-p0calc-embeds.py                 # regenerate embeds
    python scripts/gen-p0calc-embeds.py --paper-figs P  # explicit paper/figs path

Zero dependencies (stdlib only).
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DEFAULT_PAPER_FIGS = os.path.join(os.path.dirname(REPO), "paper", "figs")

ANCHOR_TOL = 0.01  # MC anchor vs pgf-curve interpolation agreement (abs fraction)


def parse_pgf_lines(text, key):
    """Parse 'KEY: (M,v) (M,v) ...' lines into ([M...],[v...])."""
    m = re.search(r"^%s:\s+(.*)$" % re.escape(key), text, re.M)
    if not m:
        raise SystemExit("fF_v4_pgf.txt: no line for %r" % key)
    pairs = re.findall(r"\(([^,]+),([^)]+)\)", m.group(1))
    if not pairs:
        raise SystemExit("fF_v4_pgf.txt: no (M,v) pairs for %r" % key)
    ms = [float(a) for a, _ in pairs]
    vs = [float(b) for _, b in pairs]
    return ms, vs


def crossings_from_curve(masses, fracs):
    """M at which the curve crosses 0.5 / 0.9 (linear in log10 M vs p)."""
    out = {}
    for name, p in (("M50", 0.5), ("M90", 0.9)):
        val = None
        for i in range(len(fracs) - 1):
            a, b = fracs[i], fracs[i + 1]
            if (a < p) != (b < p) and b != a:
                t = (p - a) / (b - a)
                lm = (1 - t) * __import__("math").log10(masses[i]) + t * __import__("math").log10(masses[i + 1])
                val = 10.0 ** lm
                break
        out[name] = val
    return out


def main():
    paper_figs = DEFAULT_PAPER_FIGS
    if "--paper-figs" in sys.argv:
        paper_figs = os.path.abspath(sys.argv[sys.argv.index("--paper-figs") + 1])
    if not os.path.isdir(paper_figs):
        raise SystemExit("paper/figs not found at %s — this generator reads the "
                         "OUTER repo and only runs in the workspace; CI must "
                         "use scripts/check-p0calc-parity.py instead." % paper_figs)

    # ---------- Paper F v0.4 ----------
    pgf = open(os.path.join(paper_figs, "fF_v4_pgf.txt"), encoding="utf-8").read()
    grid, _ = parse_pgf_lines(pgf, "eps95_riaf")
    excl = {}
    eps95 = {}
    for key, pgf_key in (("riaf", "PEXCL_riaf"),
                         ("jet", "PEXCL_jet"),
                         ("riaf_noradio", "PEXCL_riaf_noradio")):
        ms, vs = parse_pgf_lines(pgf, pgf_key)
        if len(ms) != len(grid):
            raise SystemExit("%s: %d points, grid has %d" % (pgf_key, len(ms), len(grid)))
        excl[key] = vs
    for key in ("riaf", "jet", "riaf_noradio"):
        _, vs = parse_pgf_lines(pgf, "eps95_" + key)
        eps95[key] = vs

    v4 = json.load(open(os.path.join(paper_figs, "fF_v4_exclfrac.json"), encoding="utf-8"))
    anchors_m = [6000.0, 8200.0, 40000.0]
    anchors_excl = {k: [float(x) for x in v4["p_excl_ppc"][k]] for k in excl}

    # sanity: each exact MC anchor must sit within ANCHOR_TOL of the pgf curve
    import math
    def interp(m, xs, ys):
        lg = [math.log10(x) for x in xs]
        x = math.log10(m)
        for i in range(len(xs) - 1):
            if lg[i] <= x <= lg[i + 1]:
                t = (x - lg[i]) / (lg[i + 1] - lg[i])
                return ys[i] * (1 - t) + ys[i + 1] * t
        return ys[0] if x < lg[0] else ys[-1]
    for k in excl:
        for m, a in zip(anchors_m, anchors_excl[k]):
            curve = interp(m, grid, excl[k])
            if abs(curve - a) > ANCHOR_TOL:
                raise SystemExit("anchor %s@%s = %.4f but pgf curve gives %.4f "
                                 "(> %.2f) — sources out of sync?"
                                 % (k, m, a, curve, ANCHOR_TOL))

    crossings = {k: crossings_from_curve(grid, excl[k]) for k in excl}

    ff = {
        "source": ("Paper F v0.4 outputs: fF_v4_pgf.txt PEXCL_* and eps95_* "
                   "curves (41-point grid, N_MC=40000, seed=42) with exact "
                   "anchor values from fF_v4_exclfrac.json p_excl_ppc. "
                   "Regenerated by scripts/gen-p0calc-embeds.py — a "
                   "workspace-level step; this page does not auto-track the "
                   "paper."),
        "statistic": ("posterior-predictive exclusion fraction (the v0.4 "
                      "statistic) — NOT the v0.3 per-draw statistic the page "
                      "originally shipped; the two are not comparable."),
        "M_GRID": grid,
        "EXCLFRAC": excl,
        "EPS95": eps95,
        "CROSSINGS": crossings,
        "ANCHORS_M": anchors_m,
        "ANCHORS_EXCL": anchors_excl,
    }
    with open(os.path.join(REPO, "tools", "data", "fF_v4_embed.js"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write("// GENERATED by scripts/gen-p0calc-embeds.py from the outer repo's "
                "paper/figs v0.4 outputs — edit there and regenerate, never here.\n")
        f.write("const FF_V4 = " + json.dumps(ff, indent=1) + ";\n")

    # ---------- Paper H ----------
    fh = json.load(open(os.path.join(paper_figs, "fH_posterior_plane.json"),
                        encoding="utf-8"))
    plane = {
        "source": ("paper/figs/fH_posterior_plane.json item %s (level %.2f, "
                   "bracket %s), regenerated by scripts/gen-p0calc-embeds.py"
                   % (fh["item"], fh["level"], fh["bracket"])),
        "estimators": fh["estimators"],
        "configurations": fh["configurations"],
    }
    with open(os.path.join(REPO, "tools", "data", "fH_plane_embed.js"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write("// GENERATED by scripts/gen-p0calc-embeds.py from the outer repo's "
                "paper/figs/fH_posterior_plane.json — edit there and regenerate, never here.\n")
        f.write("const FH_PLANE = " + json.dumps(plane, indent=1) + ";\n")

    print("wrote tools/data/fF_v4_embed.js and tools/data/fH_plane_embed.js")
    print("  anchors (exact MC):", json.dumps(anchors_excl))
    print("  crossings:", json.dumps(crossings))


if __name__ == "__main__":
    main()
